import os
import argparse
import asyncio
import glob
import shutil
import logging
from dotenv import load_dotenv
from google import genai
from google.genai import types
from playwright.async_api import async_playwright

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

load_dotenv()

async def generate_asset(topic: str):
    stitch_key = os.environ.get("STITCH_API_KEY")
    if not stitch_key:
        logger.error("STITCH_API_KEY is not defined in .env")
        return
        
    retry_config = types.HttpRetryOptions(initial_delay=2.0, attempts=5)
    llm_client = genai.Client(api_key=stitch_key, http_options={'retry_options': retry_config})
    
    prompt = f"Generate a hyper-modern, sleek, crisp, clean 1080x1920 vertical design with dark mode and minimalistic colors for the topic: {topic}. Provide only valid HTML/CSS code including animations that run for at least 6 seconds. Make sure the typography is bold and the content highlights key ideas of {topic}. Output ONLY the RAW HTML. Do not use Markdown formatting or codeblocks."
    
    logger.info(f"Prompting Stitch Engine (gemini-3.1-pro-preview) for topic: {topic}")
    
    try:
        response = await llm_client.aio.models.generate_content(
            model='gemini-3.1-pro-preview',
            contents=prompt,
        )
        html_content = response.text
        # Strip potential markdown formatting if model still adds it
        if html_content.startswith("```html"):
            html_content = html_content[7:]
        if html_content.endswith("```"):
            html_content = html_content[:-3]
            
    except Exception as e:
        logger.error(f"Failed to generate UI code: {e}")
        return
        
    temp_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "temp"))
    os.makedirs(temp_dir, exist_ok=True)
    temp_canvas_path = os.path.join(temp_dir, "temp_canvas.html")
    
    with open(temp_canvas_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    logger.info("HTML Canvas generated. Launching Playwright render engine...")
    
    assets_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "assets"))
    os.makedirs(assets_dir, exist_ok=True)
    raw_renders_dir = os.path.join(temp_dir, "raw_renders")
    os.makedirs(raw_renders_dir, exist_ok=True)
    
    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            context = await browser.new_context(
                viewport={"width": 1080, "height": 1920},
                record_video_dir=raw_renders_dir,
                record_video_size={"width": 1080, "height": 1920}
            )
            page = await context.new_page()
            
            logger.info("Recording video (6 seconds)...")
            await page.goto(f"file://{temp_canvas_path}")
            await page.wait_for_timeout(6000)
            
            # Closing the context flushes the video file to disk
            await context.close()
            await browser.close()
            
            # Find the generated video
            video_files = glob.glob(os.path.join(raw_renders_dir, "*.webm"))
            if video_files:
                # Latest video file
                latest_video = max(video_files, key=os.path.getctime)
                safe_topic = "".join(c for c in topic if c.isalnum() or c in (' ', '-', '_')).strip().replace(' ', '_')
                final_video_path = os.path.join(assets_dir, f"{safe_topic}.webm")
                
                shutil.move(latest_video, final_video_path)
                logger.info(f"Video saved successfully to {final_video_path}")
            else:
                logger.error("No video file generated by Playwright.")
                
    except Exception as e:
        logger.error(f"Failed to render video: {e}", exc_info=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--topic", required=True, help="Topic of the reel")
    args = parser.parse_args()
    asyncio.run(generate_asset(args.topic))
