import os
import sys
import subprocess
import json
import urllib.request
import urllib.error
from datetime import datetime
import logging

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def run_cmd(cmd, exit_on_error=True):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode != 0 and exit_on_error:
        pat = os.environ.get("GITHUB_PAT", "")
        safe_cmd = cmd.replace(pat, "***") if pat else cmd
        safe_err = result.stderr.replace(pat, "***") if pat else result.stderr
        logging.error(f"Error running '{safe_cmd}': {safe_err}")
        sys.exit(1)
    return result.stdout.strip()

def create_pr():
    pat = os.environ.get("GITHUB_PAT")
    repo = os.environ.get("GITHUB_REPO")
    
    if repo:
        repo = repo.replace("https://github.com/", "").replace("http://github.com/", "")
        if repo.endswith(".git"):
            repo = repo[:-4]
    
    if not pat or not repo:
        logging.error("Missing GITHUB_PAT or GITHUB_REPO in environment variables.")
        sys.exit(1)

    date_str = datetime.now().strftime("%Y-%m-%d-%H%M%S")
    branch_name = f"auto-update-{date_str}"
    
    # Check if there are changes to commit before branching
    status = subprocess.run("git status --porcelain", shell=True, capture_output=True, text=True).stdout.strip()
    if not status:
        logging.info("No changes to commit. Skipping PR creation.")
        return

    # Git commands
    run_cmd(f"git checkout -b {branch_name}")
    run_cmd("git add .")
    run_cmd("git commit -m 'chore: Auto-generated content & research updates'")
    
    logging.info(f"Pushing branch {branch_name} to remote...")
    run_cmd(f"git push -u https://{pat}@github.com/{repo}.git {branch_name}")
    
    # GitHub API PR Creation
    logging.info("Raising Pull Request via GitHub API...")
    url = f"https://api.github.com/repos/{repo}/pulls"
    data = {
        "title": f"Auto-Update: Content & Research ({date_str})",
        "body": "Automated Pull Request generated by Project Prism. Please review the AI-generated outputs and research before merging.",
        "head": branch_name,
        "base": "main"
    }
    
    req = urllib.request.Request(url, data=json.dumps(data).encode('utf-8'))
    req.add_header("Authorization", f"token {pat}")
    req.add_header("Accept", "application/vnd.github.v3+json")
    
    try:
        with urllib.request.urlopen(req) as response:
            response_data = json.loads(response.read().decode('utf-8'))
            pr_url = response_data.get('html_url')
            # Print specifically for the Manager Agent to capture via stdout
            print(f"PR_URL: {pr_url}")
            
        # Return to main after successful push
        run_cmd("git checkout main")
        
    except urllib.error.HTTPError as e:
        logging.error(f"Failed to create PR: {e.read().decode('utf-8')}")
        run_cmd("git checkout main")
        sys.exit(1)

if __name__ == "__main__":
    create_pr()
