import os
import argparse
import asyncio
import glob
import shutil
import logging
from playwright.async_api import async_playwright

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

async def render_local_html(html_path: str, output_name: str):
    html_path = os.path.abspath(html_path)
    if not os.path.exists(html_path):
        logger.error(f"File not found: {html_path}")
        return

    logger.info(f"Loading local canvas: {html_path}")
    logger.info("Launching Playwright render engine...")
    
    temp_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "temp"))
    assets_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "assets"))
    raw_renders_dir = os.path.join(temp_dir, "raw_renders")
    os.makedirs(assets_dir, exist_ok=True)
    os.makedirs(raw_renders_dir, exist_ok=True)
    
    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            context = await browser.new_context(
                viewport={"width": 1080, "height": 1920},
                record_video_dir=raw_renders_dir,
                record_video_size={"width": 1080, "height": 1920}
            )
            page = await context.new_page()
            
            logger.info("Recording video (6 seconds)...")
            await page.goto(f"file://{html_path}")
            await page.wait_for_timeout(6000)
            
            await context.close()
            await browser.close()
            
            video_files = glob.glob(os.path.join(raw_renders_dir, "*.webm"))
            if video_files:
                latest_video = max(video_files, key=os.path.getctime)
                safe_name = "".join(c for c in output_name if c.isalnum() or c in (' ', '-', '_')).strip().replace(' ', '_')
                final_video_path = os.path.join(assets_dir, f"{safe_name}.webm")
                
                shutil.move(latest_video, final_video_path)
                logger.info(f"SUCCESS! Video saved to: {final_video_path}")
            else:
                logger.error("No video file generated by Playwright.")
                
    except Exception as e:
        logger.error(f"Failed to render video: {e}", exc_info=True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", required=True, help="Path to the HTML file")
    parser.add_argument("--name", required=True, help="Name for the output video")
    args = parser.parse_args()
    asyncio.run(render_local_html(args.file, args.name))
